# Site information
site_name: Bash Tutorial
site_author: Monica Keith
site_description: Bash programming guide that covers a broad range of topics, useful to beginners and experienced users.

# Configuration
theme:
  name: windmill

# Custom
extra:
  logo: img/favicon.ico

# Page tree
nav:
  - Home: index.md
  - Getting started: simple_scripts.md
  - Variables: variables.md
  - Arithmetic calculations: math.md
  - Arrays: arrays.md
  - Condition testing: condition_test.md
  - Iteration: iteration.md
  - File manipulation: files.md
  - Text and CSV files: txt_csv.md
  - Image files (ImageMagick): image_magick.md
  - Image files (sips): sips.md
  - Videos: videos.md
  - PDFs (pdftk): pdftk.md
  - PDFs (qpdf): qpdf.md
  - PDFs (ghostscript): ghostscript.md
  - Advanced bash: advanced_bash.md
  - Permissions: permissions.md
  - Containers: containers.md
  - Report an error: errors.html
  - About the author: https://monicagiraldochica.github.io/
